### ISSUE TITLE
Panic on connection timeout

### ISSUE THREAD

**Issue by povilasb** [djc/quinn#292]
I've been testing changes at https://github.com/djc/quinn/pull/291 and witnessing [EndpointInner::drive_recv()](https://github.com/djc/quinn/blob/ab9e08ed359c8e356e907af8c557448c1548824a/quinn/src/endpoint.rs#L182) panics:

```
thread 'Crust-Event-Loop' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21                                                        
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.                                                                                  
stack backtrace:                                                                                                       
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace                                                                                                          
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39                                                                                                        
   1: std::sys_common::backtrace::_print                                                                                                                                 
             at src/libstd/sys_common/backtrace.rs:70                                                                                    
   2: std::panicking::default_hook::{{closure}}                                                                                
             at src/libstd/sys_common/backtrace.rs:58                                                                                                 
             at src/libstd/panicking.rs:200                                                                                                    
   3: std::panicking::default_hook                                                                                                                            
             at src/libstd/panicking.rs:215                                                                                                    
   4: std::panicking::rust_panic_with_hook                                                                                   
             at src/libstd/panicking.rs:478                                                                                              
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic
             at src/libcore/panicking.rs:49
   9: <core::option::Option<T>>::unwrap
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/macros.rs:10
  10: quinn::endpoint::EndpointInner::drive_recv
             at /home/povilas/maidsafe/quinn/quinn/src/endpoint.rs:201
  11: <quinn::endpoint::EndpointDriver as futures::future::Future>::poll
             at /home/povilas/maidsafe/quinn/quinn/src/endpoint.rs:135
  12: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
             at /home/povilas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/map_err.rs:30
  13: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /home/povilas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/mod.rs:113
  14: <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}
             at /home/povilas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:326
  15: <futures::task_impl::Spawn<T>>::enter::{{closure}}
             at /home/povilas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:396
  16: futures::task_impl::std::set
             at /home/povilas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/std/mod.rs:78
  17: <futures::task_impl::Spawn<T>>::enter
             at /home/povilas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:396
  18: <futures::task_impl::Spawn<T>>::poll_fn_notify
             at /home/povilas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:288
  19: <futures::task_impl::Spawn<T>>::poll_future_notify
             at /home/povilas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:326
20: <tokio_current_thread::scheduler::Scheduled<'a, U>>::tick
```

I did some debugging and it turns out this happens when one of the connections times out. Here's what happens in such case:

1. `proto::Connection` sends `EndpointEvent::Drained`: https://github.com/djc/quinn/blob/ab9e08ed359c8e356e907af8c557448c1548824a/quinn-proto/src/connection.rs#L502
2. this event is picked up by `EndpointInner::handle_event()` which then removes the connection from the hashmap: https://github.com/djc/quinn/blob/ab9e08ed359c8e356e907af8c557448c1548824a/quinn/src/endpoint.rs#L274
3. then UDP packet arrives which turns out belongs to the removed connection and this panics: https://github.com/djc/quinn/blob/ab9e08ed359c8e356e907af8c557448c1548824a/quinn/src/endpoint.rs#L201

Seems like [inner.handle()](https://github.com/djc/quinn/blob/ab9e08ed359c8e356e907af8c557448c1548824a/quinn/src/endpoint.rs#L188) shouldn't parse such UDP packets? Maybe `Endpoint` and `proto::Endpoint` states are out of sync?

**Comment by djc** [comment]
After the `EndpointEvent::Drained` event has been processed by the `proto::Endpoint`, it should not be possible for the UDP packet to "belong" to that connection, since the `proto::Endpoint` can no longer link it to that now-unknown connection. So what's surprising here is that the UDP packet arrives (by your timeline, after the `Drained` event is processed) and still "belongs" to the removed connection.

**Comment by povilasb** [comment]
I'm not sure if some future UDP packet with a proper CID triggers that or not, but I've been doing some debugging and it seems that when `Endpoint` removes connection `proto::Endpoint` removes this connection as well. But what is weird that in the subsequent UDP datagrams make `proto::Endpoint::handle()` yield `ConnectionHandle` which was removed according to some new connection ID. I did some logging and here's what I see just before the panic:

``` 
[endpoint_inner] new conn: ConnectionHandle(51)
[connection] send EndpointEvent::Drained: Idle timeout                             
[endpoint_inner] remove conn: ConnectionHandle(51)                     
[proto::endpoint] received EndpointEvent::Drained, removing connection: ConnectionHandle(51)                                                                             
 rm from connection_ids: ff8dc18e24163438                              
 rm from connection_ids: d45292e33575f476                    
 rm from connection_ids: b98864c06eadef8b                                 
 rm from connection_ids: 02dfa60773e056f8                    
 rm from connection_ids: e5693af35cfc9aae                                         
 rm from connection_ids: b7013e4c8b593b97                    
 rm from connection_ids: 7e0a793bcefb2fa1                                       
[proto::endpoint] handle(): got packet from removed conn: 51 - CID(359ac321af059c95) was still in connection_ids
[endpoint_inner] event for non-existant conn: ConnectionHandle(51)
```

Now I'm not sure how connection ID `359ac321af059c95` got associated with connection handle 51. To make a sense of these log messages you can take a look at https://github.com/povilasb/quinn/commit/620c5dedcbf3610abbc9d4344b71d51940bb85de

**Comment by djc** [comment]
Does a new connection arrive soon after the removal of `ConnectionHandle(51)` which might trigger the recycling of that particular handle? I wouldn't be surprised if we have race conditions there.

**Comment by Ralith** [comment]
> I did some logging and here's what I see just before the panic:

Nice work! I count 7 removed CIDs there; we attempt to maintain 8 CIDs for every connection. While the new message-passing shape of things means this won't always be the case, this might indicate that `ConnectionMeta.loc_cids` is missing a CID that's nonetheless stored in `Endpoint.connection_ids`, leading to our failure to remove it.

**Comment by povilasb** [comment]
Ralith, seems like you're right:

```
[proto::endpoint] received EndpointEvent::Drained, removing connection: ConnectionHandle(70)
  IDs (from self.connection_ids) associated with this conn handle:
   5bd7b4df68342439
   08679b5d28683c23
   e6faadaba4336b83
   dff615b62f0d1ff1
   6eacaf6ffb704343
   852b7ab65d600bbc
   f69b8a7045855aa4
   45f90b7be83d8430
  rm from connection_ids: 5bd7b4df68342439
  rm from connection_ids: dff615b62f0d1ff1
  rm from connection_ids: e6faadaba4336b83
  rm from connection_ids: 45f90b7be83d8430
  rm from connection_ids: f69b8a7045855aa4
  rm from connection_ids: 6eacaf6ffb704343
  rm from connection_ids: 852b7ab65d600bbc
[proto::endpoint] handle(): got packet from removed conn: 70 - CID(08679b5d28683c23) was still in connection_ids
```

So `ConnectionMeta.loc_cids` is missing one of the IDs, will check why.
